// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMx9DWKKDUIySi3xyK0VeEY2yvHM5__Q',
    appId: '1:389054746991:web:d1f5b4745b2c11a957589a',
    messagingSenderId: '389054746991',
    projectId: 'assemble-215ad',
    authDomain: 'assemble-215ad.firebaseapp.com',
    storageBucket: 'assemble-215ad.firebasestorage.app',
    measurementId: 'G-M99DR1Z1HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWhiFn7u35D_L2SLqfEh0uYNRxq1mY9A',
    appId: '1:389054746991:android:bb4d0d957117d32257589a',
    messagingSenderId: '389054746991',
    projectId: 'assemble-215ad',
    storageBucket: 'assemble-215ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ICu5oM3K_-4S3HaNuppM5fhjaWDbluk',
    appId: '1:389054746991:ios:c032e9a08c4ccd3457589a',
    messagingSenderId: '389054746991',
    projectId: 'assemble-215ad',
    storageBucket: 'assemble-215ad.firebasestorage.app',
    iosClientId: '389054746991-v43uoc3gre9dd36e3p0tm6k91ka6ksol.apps.googleusercontent.com',
    iosBundleId: 'com.example.assemble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ICu5oM3K_-4S3HaNuppM5fhjaWDbluk',
    appId: '1:389054746991:ios:c032e9a08c4ccd3457589a',
    messagingSenderId: '389054746991',
    projectId: 'assemble-215ad',
    storageBucket: 'assemble-215ad.firebasestorage.app',
    iosClientId: '389054746991-v43uoc3gre9dd36e3p0tm6k91ka6ksol.apps.googleusercontent.com',
    iosBundleId: 'com.example.assemble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKMx9DWKKDUIySi3xyK0VeEY2yvHM5__Q',
    appId: '1:389054746991:web:460112f12c6e665f57589a',
    messagingSenderId: '389054746991',
    projectId: 'assemble-215ad',
    authDomain: 'assemble-215ad.firebaseapp.com',
    storageBucket: 'assemble-215ad.firebasestorage.app',
    measurementId: 'G-F154R8G0ZG',
  );
}
